main: com.jcgrant.jccraft.JCCraft
name: JCCraft
version: 0.0.1
author: JCGrant
description: A set of plugins used on the JCCraft server
commands:
  chat:
    description: Set your chat distance to local or global
    usage: /chat <global/local>
  discord:
    description: Commands to talk with JC Craft Discord server
    usage: /discord